imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    auto_reload: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true,
        metadata_cache_driver:
          type: service
          id: doctrine_cache.providers.metadata_cache
        query_cache_driver:
          type: service
          id: doctrine_cache.providers.query_cache
        result_cache_driver:
          type: service
          id: doctrine_cache.providers.result_cache
        dql:
            datetime_functions:
              MONTH: DoctrineExtensions\Query\Mysql\Month
              YEAR: DoctrineExtensions\Query\Mysql\Year
              MONTHNAME: DoctrineExtensions\Query\Mysql\MonthName


doctrine_cache:
  providers:
    metadata_cache:
      file_system:
        extension: ".cache"
        directory: "%kernel.cache_dir%/doctrine/metadata"
    query_cache:
      file_system:
        extension: ".cache"
        directory: "%kernel.cache_dir%/doctrine/query"
    result_cache:
      file_system:
        extension: ".cache"
        directory: "%kernel.cache_dir%/doctrine/result"

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOS user login
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "wazir.ahmadzai@gmail.com"
        sender_name: "Afg-PolioDB"
    registration:
            form:
                type: AppBundle\Form\RegistrationType
    profile:
            form:
                type: AppBundle\Form\ProfileType

# doctrine migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# sonata configuration
#sonata_block:
#    default_contexts: [cms]
#    blocks:
#
#        # enable the SonataAdminBundle block
#        sonata.admin.block.admin_list:
#            contexts:   [admin]

# knp Menu
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: my_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

# vichuploader
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
            imported_file:
                uri_prefix:         /data_files
                upload_destination: '%kernel.root_dir%/../web/data_files'
                namer:
                      service: vich_uploader.namer_property
                      options: { property: 'nameSlug'}

                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

# jwt configuration
lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        3600