app:
    resource: '@AppBundle/Controller/'
    type: annotation
    options:
      expose: true

#FOS Routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Sonata Admin Routing
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# sg data table bundle routes
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation

# fos routing js
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"