# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#http_basic: ~

# https://symfony.com/doc/current/security/form_login_setup.html

# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PARTNER: PARTIAL_VIEWER
        ROLE_NORMAL_USER:  ROLE_VIEWER, ROLE_USER
        ROLE_COVID19_EDITOR: ROLE_NORMAL_USER
        ROLE_EDITOR:  ROLE_NORMAL_USER
        ROLE_ADMIN: ROLE_EDITOR, ROLE_SUPER_ADMIN, ROLE_COVID19_EDITOR


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # firewall for api authentication
        api:
            pattern: ^/api/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain: ~
                secure: false
                user_provider: fos_userbundle

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api_test, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/resetting/request, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/send-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/reset/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*, role: ROLE_USER}
