# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#http_basic: ~

# https://symfony.com/doc/current/security/form_login_setup.html

# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PARTNER: PARTIAL_VIEWER
        ROLE_NORMAL_USER:  ROLE_VIEWER, ROLE_USER
        ROLE_EDITOR:  ROLE_NORMAL_USER
        ROLE_ADMIN: ROLE_EDITOR, ROLE_SUPER_ADMIN


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/request, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/send-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/reset/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*, role: ROLE_USER}
